server {
    listen 80;
    server_name spaceshooter.tnt-tech.io.vn;

    root /var/www/space-vibe-shooter; # Đường dẫn thư mục chứa code
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }

    # Cấu hình cache cho assets static
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
